### ISSUE TITLE
Editing /etc/nextdns.conf does not persist on reboot

### ISSUE THREAD

**Issue by andrewjmoser** [mbierman/Firewalla-NextDNS-CLI-install#2]
Firewalla Gold Plus, Box version 1.9750, App version 1.52.   I have like 6 different NextDNS configs, multiple conditional forwarders for my particular setup, so I ran your script as the readme said, just inputting my main config ID and subnet info, everything installed perfect.     I then edited /etc/nextdns.conf and added all my other config ID's, conditional forawrders, etc...     Restarted NextDNS and it all was working, multiple configs, forwarding, etc...   When I rebooted my Firewalla, all those changes I made to nextdns.conf, are gone.   Is this expected behavior?  If so, what is the best way to run your script with all those extra options that I would need?

**Comment by mbierman** [comment]
Hi Andrew! 

> I ran your script as the readme said, just inputting my main config ID and subnet info, everything installed perfect.

Where did you edit your config ID and subnet info? 

> I then edited /etc/nextdns.conf and added all my other config ID's, conditional forawrders, etc... Restarted NextDNS and it all was working, multiple configs, forwarding, etc... When I rebooted my Firewalla, all those changes I made to nextdns.conf, are gone. Is this expected behavior? If so, what is the best way to run your script with all those extra options that I would need?

Yes, this is expected. You should not edit `/etc/nexttdns.conf`. Edit the install script at `/home/pi/.firewalla/config/post_main.d/install_nextdnscli.sh`  this will run automtically on every reboot and set up things as you define in installer, so if you edit that to be what you want. The script will check to see if anything is missing and add it for you. Anything already in place is left alone.

These lines are what you need to focus on: 
```
sudo nextdns install \
-config ${IP}/24=${id} \
-report-client-info -cache-size=10MB -max-ttl=5s -discovery-dns ${IP} -listen ${IP}:5555 
```

You can use the existing IP and id variables if you like, you can add variables if you like, you can hardcode everything there if you prefer.

**Comment by andrewjmoser** [comment]
I guess I am not getting the context of pieces of the script correct, 

If I set variables at the beginning like this for my 5 configs like this.

id1=12345
IP1=1.2.3.4
id2=12345
IP2=1.2.3.4
id3=12345
IP3=1.2.3.4
id4=12345
IP4=1.2.3.4
id5=12345
IP5=12345

Then I edit the lines you mention like this?  Git won't display the $ and {} but they are there

sudo nextdns install \
-config ${IP1}/24=${id1} \
-config ${IP2}/24=${id2} \
-config ${IP3}/24=${id3} \
-config ${IP4}/24=${id4} \
-config ${I51}/24=${id5} \
-report-client-info -cache-size=10MB -max-ttl=5s -discovery-dns ${IP} -listen ${IP}:5555

When I do that I run it and get an error that I have no config set.  Im sure I am missing something simple.

**Comment by mbierman** [comment]
So it could be you don’t have the right information, I’m not sure of your network. What you have outlined would be five completely different networks. Every device on each network would use the Profile you specify.

As the examples include:
You can also put a config for an individual mac address like so. Edit to include your actual MAC address and put these in the config above.
 -config xx:yy:zz:aa:bb:cc=${id} \

Note too, on all but the last line of this command, put a backslash at the end of the line.

If that doesn’t get you there, maybe you can describe your network and the different NextDNS profiles you want to apply.

**Comment by mbierman** [comment]
@andrewjmoser is this resolved for you?

**Comment by andrewjmoser** [comment]
Yep, I am good.   I had to just had to keep trying and checking the syntax, once I got it right it worked and has been working since.
