### ISSUE TITLE
 Enabling Unbound bypasses NextDNS

### ISSUE THREAD

**Issue by Coder84619** [mbierman/Firewalla-NextDNS-CLI-install#3]
I have NextDNS configured for both LAN and Wireguard clients. Visiting test.nextdns.io validates that all is well with unbound disabled. However, when I enable Unbound and re-run the test, both LAN and Wireguard clients are unconfigured and use my IPS DNS. 

I saw in the instructions that it should work with Unbound enabled. Did I do something wrong?

**Comment by Coder84619** [comment]
Here's my config:

pi@Firewalla:~ (Firewalla) $ nextdns config
auto-activate false
cache-size 10MB
report-client-info true
mdns all
bogus-priv true
listen 10.13.2.1:5555
listen localhost:53
log-queries false
max-ttl 5s
use-hosts true
setup-router false
control /var/run/nextdns.sock
cache-max-age 0s
detect-captive-portals false
hardened-privacy false
config 10.189.114.0/24=xxxxxx
config 10.13.2.0/24=xxxxxx
discovery-dns 10.13.2.1
timeout 5s
max-inflight-requests 256

**Comment by mbierman** [comment]
You can't have Unbound active on the same device as nextDNS CLI. they are mutually exclusive.

**Comment by Coder84619** [comment]
Ok....then I'd humbly suggest updating this wording:

NextDNS CLI runs nicely with Firewalla Unbound, but so far it I have not been successful in getting it to work with Firewalla DNS over HTTP (DoH) but NextDNS CLI uses DoH.

**Comment by mbierman** [comment]
Yes, please check the current wording and see if you think it clarifies sufficiently. And sorry about any confusion.

**Comment by Coder84619** [comment]
> Yes, please check the current wording and see if you think it clarifies sufficiently. And sorry about any confusion.

Yes, much better, thanks!

**Comment by Coder84619** [comment]
Wording update clarified the situation.
