### ISSUE TITLE
NextDNS failed to see device names after Firewalla reboot

### ISSUE THREAD

**Issue by Coder84619** [mbierman/Firewalla-NextDNS-CLI-install#4]
I have a Firewalla Gold+, and had NextDNS CLI running per your script just fine. NextDNS web logs showed device names being passed along. Yesterday I rebooted my Firewalla and just happened to look at NextDNS web logs this morning. 100% of the requests were just coming from my public ISP address. I SSH'd into Firewalla and ran nextdns status, and it returned "running". I then did nextdns config and the proper config was returned. I then re-ran the install_nextdnslcli.sh and instantly NextDNS logs were getting device names. 

So something happened during the reboot.

**Comment by mbierman** [comment]
Once in a while something seems to go awry. I wrote a script https://github.com/mbierman/Firewalla-NextDNS-CLI-install/blob/main/nextdnstest.sh which tests to see if nextdns is running and restart it if not. However, the mechanism nextens provides seems somewhat unreliable. 

`sudo nextdns status`

I raised this with nextdns but their support is iffy at best. I have found that in reality it is pretty rare for things to go wrong (at least for me) so I just kind of accepted this. 

You could rerun the installation script via a cronjob if you like. It won't do any harm.

**Comment by Coder84619** [comment]
Is there a way to run the 'install' script as part of a boot-up sequence? That's when it seemed to fail for me.

**Comment by mbierman** [comment]
Yes! It should be located in /home/pi/.firewalla/config/post_main.d/install_nextdnscli.sh

which means it will be executed after every reboot automatically.
