### ISSUE TITLE
How to upgrade NextDNS CLI version?

### ISSUE THREAD

**Issue by Coder84619** [mbierman/Firewalla-NextDNS-CLI-install#5]
Stuck on v1.38 and don't see an obvious way to upgrade to latest version. What is the procedure?

**Comment by mbierman** [comment]
I'm not sure why grabbing "latest" doesn't get the upgrade. I'll have to look into that. But upgrading is easy: 

`sudo nextdns upgrade`

I will add this to the installation.

**Comment by Coder84619** [comment]
I checked my version today, and it's now on 1.39.4.

**Comment by mbierman** [comment]
Thanks for the reminder. I updated to include an upgrade check in the latest version.
