### ISSUE TITLE
Feature Request: Add guest network variables

### ISSUE THREAD

**Issue by Coder84619** [mbierman/Firewalla-NextDNS-CLI-install#7]
I like how you have variables setup for VPNs so we can use different profiles. I have an isolated guest network with unique IP address space. I modified your install script to add the configuration line. Given that guest networks are probably fairly common, it might make sense to build in support so that adding a network is as easy as your VPN config. 

For reference here's my config:

sudo nextdns install \
-config 192.168.193.1/24=bxxxxx \
-config $WireGuard/24=$VPNID \
-config ${IP}/24=${id} \
-report-client-info -cache-size=10MB -max-ttl=5s -discovery-dns ${IP} -listen ${IP}:5555

**Comment by mbierman** [comment]
I added some documentation around this. I could make variables for so many kinds of situations and make the command conditional (e.g. if there is a guest network, include this...) but I think it is almost always going to be something the user has to customize ultimately. If you have ideas how to organize this I'm open to hearing them.
