### ISSUE TITLE
Firewalla local requests not using NextDNS CLI (un-encrypted DNS leakage)

### ISSUE THREAD

**Issue by Coder84619** [mbierman/Firewalla-NextDNS-CLI-install#8]
I setup NextDNS CLI for both of my networks (primary/guest). It appears all of the requests from my LAN devices are using DoH via NextDNS CLI analytics. However, there are a few DNS requests happening every minute that are not encrypted per NextDNS logs:

github.com
firewalla.encipher.io 

I suspect Firewalla itself is doing these lookups. But why 1) Is it doing a github DNS lookup every minute and 2) Why isn't it honoring the NextDNS CLI profile setting and getting the DoH treatment?

**Comment by mbierman** [comment]
Firewalla has to talk to those for many things. When you use the app remotely for example. It also uses those as connectivity tests (unless you change them). This is normal. Nothing to worry about.
